export enum Properties {
    //GET
    GET_QUERY = "GET_QUERY",
    GET_COLUMN = "GET_COLUMN",
    GET_COLUMNNAME = "GET_COLUMNNAME",
    GET_COLUMNVALUE = "GET_COLUMNVALUE",
  
    //PATCH
    PATCH_RECORDID = "PATCH_RECORDID",
    PATCH_DATA = "PATCH_DATA",
    PATCH_COLUMNS = "PATCH_COLUMNS",
    PATCH_COLUMN = "PATCH_COLUMN",
    PATCH_COLUMNNAME = "PATCH_COLUMNNAME",
    PATCH_COLUMNVALUE = "PATCH_COLUMNVALUE",
  
    //GET and PATCH
    ENTITYNAME = "ENTITYNAME",
  
    OPTIONSET_ENTITYNAME = "OPTIONSET_ENTITYNAME",
    OPTIONSET_ATTRIBUTENAME = "OPTIONSET_ATTRIBUTENAME",
  
    GLOBAL_ATTRIBUTENAME = "GLOBAL_ATTRIBUTENAME",
  
    ENTITY_ID = "ENTITY_ID",
    ENTITY_NAME = "ENTITY_NAME",
  
    TYPE = "TYPE",
    OPERATION = "OPERATION",

    //DELETE
    DELETE_RECORDID = "delete_recordid",
}